version: '3'
services:
  express:
    build: ./backend
    container_name: express-app
    restart: always
    ports:
      - "3000:3000"   # Пробрасываем порт наружу

  react:
    build: ./frontend
    container_name: react-app
    restart: always
    ports:
      - "3001:80"     # Пробрасываем порт наружу
