version: '3'
services:
  express:
    build: ./backend
    container_name: express-app
    restart: always

  react:
    build: ./frontend
    container_name: react-app
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - express
      - react